---
apiVersion: v1
kind: Secret
metadata:
  name: hpgrahsl-dryrun-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevLab/hpgrahsl-dryrun-gateway-app-gitops
